github: juskalalie
patreon: stephenbeechen
custom:
  - https://www.buymeacoffee.com/juskalalie
  - https://www.paypal.com/paypalme/stephenbeechen
  - https://github.com/juskalalie/hassio-filenio-backup/blob/master/donate-crypto.md
