# How to use:
#    cd hassio-filenio-backup
#    gcloud config set project hassio-filenio 
#    gcloud builds submit --config cloudbuild-dev.yaml --substitutions _DOCKERHUB_PASSWORD=<PASSWORD>

steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args: ["-c", "docker login --username=juskalalie --password=${_DOCKERHUB_PASSWORD}"]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile-addon',  '-t', 'juskalalie/hassio-filenio-backup-dev-amd64:${_VERSION}', "--build-arg", "BUILD_FROM=homeassistant/amd64-base", '.' ]
substitutions:
  _DOCKERHUB_PASSWORD: "define me" # default value
  _VERSION: "dev-testing" # default value
images:
- "juskalalie/hassio-filenio-backup-dev-amd64:${_VERSION}"
        
