name: push_to_staging
concurrency:
  # Only run this workflow one at a time, and cancel any in progress
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
    branches:
      - dev
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Staging Verison Override'
        # Default value if no value is explicitly provided
        default: 'increment'

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    # Check out the current branch
    - uses: actions/checkout@v4
      with:
        path: dev
    # Check out the staging barnch
    - uses: actions/checkout@v4
      with:
        path: staging
        repository: juskalalie/hgdb-dev-staging
    - run: |
          python3 staging/update.py dev staging
